services:
# Minecraft server
  minecraft:
    image: itzg/minecraft-server
    environment:
      # Indicates the server type
      TYPE: "PAPER"

      # Sets the server name
      SERVER_NAME: "Nansy"

      # By default the value should always be TRUE
      EULA: "true"

      # server setting that configures whether or not players 
      ONLINE_MODE: "true"

      # If you would like to docker attach to the Minecraft server console with color and interactive capabilities, then add
      EXEC_DIRECTLY: "true"
      # Allocates GB of RAM to the server
      MEMORY: 1G
      # Allows server to announce when a player gets an achievement.
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      
      # The image a server icon
      ICON: "https://indianmemetemplates.com/wp-content/uploads/say-my-name.jpg"
      
      # The difficulty level (default: easy) 
      DIFFICULTY: "hard"
      
      # The message of the day, shown below each server entry in the client UI
      MOTD: "§cWelcome to §r §nServer"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

# Monitoring 
  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: minecraft
      DEBUG: "true"
    depends_on:
      - minecraft
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus_manifest/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.3}
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  data: {}
  prometheus-tsdb: {}
  grafana-lib: {}